[global]
log_level = 'error'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[[chains]]
id = 'ibc-eth-0'
genesis_time = 1606824023
genesis_root = "0x4b363db94e286120d76eb905340fdd4e54bfe9f06bf33ff6cf5ad27f511bfe95"
initial_checkpoint = "0x51cd6fb4ee0efd15c8ec91e50226ee8aeca2d5bc31422cd69a8a9acf9660318e"
key_name = 'relayer_eth_wallet'
rpc_addr_pool = ['http://127.0.0.1:8545']
rpc_port = 8545
[chains.forks]
genesis = { epoch = 0, fork_version = "0x00000000" }
altair = { epoch = 74240, fork_version = "0x01000000" }
bellatrix = { epoch = 144896, fork_version = "0x02000000" }
capella = { epoch = 194048, fork_version = "0x03000000" }

[[chains]]
id = 'ibc-ckb-0'
ckb_rpc= "http://127.0.0.1:8114"
ckb_indexer_rpc = "http://127.0.0.1:8114"
lightclient_contract_typeargs = "0xf49ce32397c6741998b04d7548c5ed372007424daf67ee5bfadaefec3c865781"
lightclient_lock_typeargs = "0xfbe09e8ff3e5f3d0fab7cc7431feed2131846184d356a9626639f55e7f471846"
client_type_args = { cells_count = 4 }
minimal_updates_count = 1
key_name = "relayer_ckb_wallet"
data_dir = "./ckb_mmr_storage"

# [[chains]]
# id = 'ckb-test'
# ckb_rpc = "https://testnet.ckbapp.dev"
# ckb_indexer_rpc = "https://testnet.ckbapp.dev"
# lightclient_contract_typeargs = "0x70a8cb9881d7f5523145e99a582a08524ab4e7da6688bc1090e958462627fdd4"
# lightclient_lock_typeargs = "0xecc3a408395f890d4da68c2be48649ef1d4f3e9ca03946e94327bbb961239232"
# client_type_args = { cells_count = 4, type_id = "0x9faa95c83467ba771fc04c1f133fd300cbc01c606a1b99a1482485c5a526a2d4" }
# minimal_updates_count = 1
# key_name = "ckb-test-wallet"
# data_dir = "./ckb_mmr_storage_test"